name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - master
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add GitLab Remote
        run: |
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/akshaybhor4031-group/studentdemo.git

      - name: Push all branches
        run: |
          git push gitlab --all --force

      - name: Push all tags
        run: |
          git push gitlab --tags --force
